excluded:
  - Pods
  - Carthage
  - Generated
  - .git/
  - script/
  - FIRESTORE/

indentation_width: 2

line_length:
  warning: 120
  error: 200
  ignores_comments: true

opt_in_rules:
  - empty_count
  - sorted_imports
  - indentation_width
